# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it

source:
  git_url: ../

{% if "GIT_DESCRIBE_NUMBER" not in environ %}
{% set VERSION_NUMBER = "0+unknown"  %}
{% elif GIT_DESCRIBE_NUMBER > '0'  %}
{% set VERSION_NUMBER = GIT_DESCRIBE_TAG[1:] + ".post" + GIT_DESCRIBE_NUMBER %}
{% else  %}
{% set VERSION_NUMBER = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

package:
  name: microdrop.device-loader-ui-plugin
  version: {{ VERSION_NUMBER }}

build:
  number: 0
  script: python -m mpm.bin.build --versionNumber {{ VERSION_NUMBER }}

requirements:
  build:
    - flatland-fork
    - flatland-helpers
    - microdrop-plugin-manager >=0.5.post103-0
    - pandas
    - path_helpers >=0.2.post4
    - pandas-helpers
    - paho-mqtt-helpers >=0.2
    - si-prefix

  run:
    - flatland-fork
    - flatland-helpers
    - pandas
    - path_helpers >=0.2.post4
    - pandas-helpers
    - paho-mqtt-helpers >=0.2
    - si-prefix

about:
  home: https://github.com/Lucaszw/device-loader-ui-plugin
  license: GPL
